{"uid":"95099a215185e560","name":"test_legacy_noarch_python","fullName":"tests.test_api_build#test_legacy_noarch_python","historyId":"feb96acc35227ee5eec272cc2f5d058b","time":{"start":1668029148864,"stop":1668029654154,"duration":505290},"status":"skipped","statusMessage":"XFAIL parallel verify/execute in conda 4.7 breaks legacy noarch, which depends on having the env files present before pre-link scripts are run.\n\nconda.exceptions.LinkError: pre-link script failed for package file:///C:/Users/runneradmin/cbtmp/popen-gw1/test_legacy_noarch_python0::noarch_test_package-1.0-py_0\nlocation of failed script: C:\\Users\\runneradmin\\Miniconda3\\pkgs\\noarch_test_package-1.0-py_0\\Scripts\\.noarch_test_package-pre-link.bat\n==> script messages <==\n<None>\n==> script output <==\nstdout: \nstderr: '\"C:\\Users\\runneradmin\\cbtmp\\popen-gw1\\test_legacy_noarch_python0\\noarch_test_package_1668029148895\\_test_env\\python.exe\"' is not recognized as an internal or external command,\r\noperable program or batch file.\r\n\nreturn code: 1","statusTrace":"Traceback (most recent call last):\n  File \"D:\\a\\conda-build\\conda-build\\tests\\test_api_build.py\", line 823, in test_legacy_noarch_python\n    output = api.build(os.path.join(metadata_dir, \"_legacy_noarch_python\"),\n  File \"D:\\a\\conda-build\\conda-build\\conda_build\\api.py\", line 180, in build\n    return build_tree(\n  File \"D:\\a\\conda-build\\conda-build\\conda_build\\build.py\", line 3110, in build_tree\n    test(pkg, config=metadata.config.copy(), stats=stats)\n  File \"D:\\a\\conda-build\\conda-build\\conda_build\\build.py\", line 2900, in test\n    environ.create_env(metadata.config.test_prefix, actions, config=metadata.config,\n  File \"D:\\a\\conda-build\\conda-build\\conda_build\\environ.py\", line 908, in create_env\n    execute_actions(actions, index)\n  File \"C:\\Users\\runneradmin\\Miniconda3\\lib\\site-packages\\conda\\common\\io.py\", line 86, in decorated\n    return f(*args, **kwds)\n  File \"C:\\Users\\runneradmin\\Miniconda3\\lib\\site-packages\\conda\\plan.py\", line 324, in execute_actions\n    execute_instructions(plan, index, verbose)\n  File \"C:\\Users\\runneradmin\\Miniconda3\\lib\\site-packages\\conda\\plan.py\", line 535, in execute_instructions\n    cmd(state, arg)\n  File \"C:\\Users\\runneradmin\\Miniconda3\\lib\\site-packages\\conda\\instructions.py\", line 73, in UNLINKLINKTRANSACTION_CMD\n    unlink_link_transaction.execute()\n  File \"C:\\Users\\runneradmin\\Miniconda3\\lib\\site-packages\\conda\\core\\link.py\", line 284, in execute\n    self._execute(tuple(concat(interleave(self.prefix_action_groups.values()))))\n  File \"C:\\Users\\runneradmin\\Miniconda3\\lib\\site-packages\\conda\\core\\link.py\", line 670, in _execute\n    run_script(target_prefix if is_unlink else prec.extracted_package_dir,\n  File \"C:\\Users\\runneradmin\\Miniconda3\\lib\\site-packages\\conda\\core\\link.py\", line 1255, in run_script\n    raise LinkError(message)\nconda.exceptions.LinkError: pre-link script failed for package file:///C:/Users/runneradmin/cbtmp/popen-gw1/test_legacy_noarch_python0::noarch_test_package-1.0-py_0\nlocation of failed script: C:\\Users\\runneradmin\\Miniconda3\\pkgs\\noarch_test_package-1.0-py_0\\Scripts\\.noarch_test_package-pre-link.bat\n==> script messages <==\n<None>\n==> script output <==\nstdout: \nstderr: '\"C:\\Users\\runneradmin\\cbtmp\\popen-gw1\\test_legacy_noarch_python0\\noarch_test_package_1668029148895\\_test_env\\python.exe\"' is not recognized as an internal or external command,\r\noperable program or batch file.\r\n\nreturn code: 1","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"tmp_path_factory","time":{"start":1668028885839,"stop":1668028885839,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false},{"name":"testing_workdir","time":{"start":1668029148864,"stop":1668029148864,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false},{"name":"tmpdir","time":{"start":1668029148864,"stop":1668029148864,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false},{"name":"tmp_path","time":{"start":1668029148864,"stop":1668029148864,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false},{"name":"testing_config","time":{"start":1668029148864,"stop":1668029148864,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false}],"testStage":{"status":"skipped","statusMessage":"XFAIL parallel verify/execute in conda 4.7 breaks legacy noarch, which depends on having the env files present before pre-link scripts are run.\n\nconda.exceptions.LinkError: pre-link script failed for package file:///C:/Users/runneradmin/cbtmp/popen-gw1/test_legacy_noarch_python0::noarch_test_package-1.0-py_0\nlocation of failed script: C:\\Users\\runneradmin\\Miniconda3\\pkgs\\noarch_test_package-1.0-py_0\\Scripts\\.noarch_test_package-pre-link.bat\n==> script messages <==\n<None>\n==> script output <==\nstdout: \nstderr: '\"C:\\Users\\runneradmin\\cbtmp\\popen-gw1\\test_legacy_noarch_python0\\noarch_test_package_1668029148895\\_test_env\\python.exe\"' is not recognized as an internal or external command,\r\noperable program or batch file.\r\n\nreturn code: 1","statusTrace":"Traceback (most recent call last):\n  File \"D:\\a\\conda-build\\conda-build\\tests\\test_api_build.py\", line 823, in test_legacy_noarch_python\n    output = api.build(os.path.join(metadata_dir, \"_legacy_noarch_python\"),\n  File \"D:\\a\\conda-build\\conda-build\\conda_build\\api.py\", line 180, in build\n    return build_tree(\n  File \"D:\\a\\conda-build\\conda-build\\conda_build\\build.py\", line 3110, in build_tree\n    test(pkg, config=metadata.config.copy(), stats=stats)\n  File \"D:\\a\\conda-build\\conda-build\\conda_build\\build.py\", line 2900, in test\n    environ.create_env(metadata.config.test_prefix, actions, config=metadata.config,\n  File \"D:\\a\\conda-build\\conda-build\\conda_build\\environ.py\", line 908, in create_env\n    execute_actions(actions, index)\n  File \"C:\\Users\\runneradmin\\Miniconda3\\lib\\site-packages\\conda\\common\\io.py\", line 86, in decorated\n    return f(*args, **kwds)\n  File \"C:\\Users\\runneradmin\\Miniconda3\\lib\\site-packages\\conda\\plan.py\", line 324, in execute_actions\n    execute_instructions(plan, index, verbose)\n  File \"C:\\Users\\runneradmin\\Miniconda3\\lib\\site-packages\\conda\\plan.py\", line 535, in execute_instructions\n    cmd(state, arg)\n  File \"C:\\Users\\runneradmin\\Miniconda3\\lib\\site-packages\\conda\\instructions.py\", line 73, in UNLINKLINKTRANSACTION_CMD\n    unlink_link_transaction.execute()\n  File \"C:\\Users\\runneradmin\\Miniconda3\\lib\\site-packages\\conda\\core\\link.py\", line 284, in execute\n    self._execute(tuple(concat(interleave(self.prefix_action_groups.values()))))\n  File \"C:\\Users\\runneradmin\\Miniconda3\\lib\\site-packages\\conda\\core\\link.py\", line 670, in _execute\n    run_script(target_prefix if is_unlink else prec.extracted_package_dir,\n  File \"C:\\Users\\runneradmin\\Miniconda3\\lib\\site-packages\\conda\\core\\link.py\", line 1255, in run_script\n    raise LinkError(message)\nconda.exceptions.LinkError: pre-link script failed for package file:///C:/Users/runneradmin/cbtmp/popen-gw1/test_legacy_noarch_python0::noarch_test_package-1.0-py_0\nlocation of failed script: C:\\Users\\runneradmin\\Miniconda3\\pkgs\\noarch_test_package-1.0-py_0\\Scripts\\.noarch_test_package-pre-link.bat\n==> script messages <==\n<None>\n==> script output <==\nstdout: \nstderr: '\"C:\\Users\\runneradmin\\cbtmp\\popen-gw1\\test_legacy_noarch_python0\\noarch_test_package_1668029148895\\_test_env\\python.exe\"' is not recognized as an internal or external command,\r\noperable program or batch file.\r\n\nreturn code: 1","steps":[],"attachments":[{"uid":"3a8107c654961c","name":"log","source":"3a8107c654961c.txt","type":"text/plain","size":1890},{"uid":"ac2fd30c925fdef","name":"stdout","source":"ac2fd30c925fdef.txt","type":"text/plain","size":19042},{"uid":"4872eae627925f54","name":"stderr","source":"4872eae627925f54.txt","type":"text/plain","size":465}],"parameters":[],"stepsCount":0,"attachmentsCount":3,"shouldDisplayMessage":true,"hasContent":true},"afterStages":[{"name":"testing_workdir::return_to_saved_path","time":{"start":1668029654154,"stop":1668029654170,"duration":16},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false}],"labels":[{"name":"tag","value":"@pytest.mark.xfail(True, reason='parallel verify/execute in conda 4.7 breaks legacy noarch, which depends on having the env files present before pre-link scripts are run.')"},{"name":"tag","value":"sanity"},{"name":"parentSuite","value":"tests"},{"name":"suite","value":"test_api_build"},{"name":"host","value":"fv-az211-563"},{"name":"thread","value":"3484-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.test_api_build"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[],"history":{"statistic":{"failed":0,"broken":0,"skipped":2,"passed":0,"unknown":0,"total":2},"items":[{"uid":"b0aca8acaf0dea03","status":"skipped","statusDetails":"XFAIL parallel verify/execute in conda 4.7 breaks legacy noarch, which depends on having the env files present before pre-link scripts are run.\n\nconda.exceptions.LinkError: pre-link script failed for package file:///C:/Users/runneradmin/cbtmp/popen-gw1/test_legacy_noarch_python0::noarch_test_package-1.0-py_0\nlocation of failed script: C:\\Users\\runneradmin\\Miniconda3\\pkgs\\noarch_test_package-1.0-py_0\\Scripts\\.noarch_test_package-pre-link.bat\n==> script messages <==\n<None>\n==> script output <==\nstdout: \nstderr: '\"C:\\Users\\runneradmin\\cbtmp\\popen-gw1\\test_legacy_noarch_python0\\noarch_test_package_1668029148895\\_test_env\\python.exe\"' is not recognized as an internal or external command,\r\noperable program or batch file.\r\n\nreturn code: 1","time":{"start":1668029148864,"stop":1668029654154,"duration":505290}}]},"tags":["@pytest.mark.xfail(True, reason='parallel verify/execute in conda 4.7 breaks legacy noarch, which depends on having the env files present before pre-link scripts are run.')","sanity"]},"source":"95099a215185e560.json","parameterValues":[]}