[32mINFO    [0m binstar:config.py:149 Using Anaconda API: https://api.anaconda.org
[35mDEBUG   [0m binstar:config.py:152 Using token from command line args
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:1003 Starting new HTTPS connection (1): api.anaconda.org:443
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:456 https://api.anaconda.org:443 "GET /package/conda_build_test/test_token_upload_6114cf4e7557479db71ea632a1a64ab1 HTTP/1.1" 404 None
[32mINFO    [0m conda_build.variants:variants.py:235 Adding in variants from config.variant
[32mINFO    [0m conda_build.metadata:metadata.py:854 Attempting to finalize metadata for test_token_upload_6114cf4e7557479db71ea632a1a64ab1
[32mINFO    [0m conda_build.build:build.py:2280 Packaging test_token_upload_6114cf4e7557479db71ea632a1a64ab1
[33mWARNING [0m conda_build.build:build.py:1627 No files or script found for output test_token_upload_6114cf4e7557479db71ea632a1a64ab1
[32mINFO    [0m conda_build.utils:utils.py:1970 Renaming work directory '/Users/runner/work/_temp/serial/test_token_upload0/test_token_upload_6114cf4e7557479db71ea632a1a64ab1_1673042586150/work' to '/Users/runner/work/_temp/serial/test_token_upload0/test_token_upload_6114cf4e7557479db71ea632a1a64ab1_1673042586150/work_moved_test_token_upload_6114cf4e7557479db71ea632a1a64ab1-1.0-1_osx-64_main_build_loop'
[32mINFO    [0m conda_build.utils:utils.py:1977 shutil.move(work)=/Users/runner/work/_temp/serial/test_token_upload0/test_token_upload_6114cf4e7557479db71ea632a1a64ab1_1673042586150/work, dest=/Users/runner/work/_temp/serial/test_token_upload0/test_token_upload_6114cf4e7557479db71ea632a1a64ab1_1673042586150/work_moved_test_token_upload_6114cf4e7557479db71ea632a1a64ab1-1.0-1_osx-64_main_build_loop)
[32mINFO    [0m binstar:config.py:149 Using Anaconda API: https://api.anaconda.org
[35mDEBUG   [0m binstar:config.py:152 Using token from command line args
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:1003 Starting new HTTPS connection (1): api.anaconda.org:443
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:456 https://api.anaconda.org:443 "GET /package/conda_build_test/test_token_upload_6114cf4e7557479db71ea632a1a64ab1 HTTP/1.1" 404 None