[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:1007 Starting new HTTPS connection (1): cran.r-project.org:443
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:465 https://cran.r-project.org:443 "GET /src/contrib/ HTTP/1.1" 200 None
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:465 https://cran.r-project.org:443 "GET /src/contrib/Archive/ HTTP/1.1" 200 None
[33mWARNING [0m conda_build.source:source.py:64 No hash (md5, sha1, sha256) provided for source-meanr_0.1-5.tar.gz.  Source download forced.  Add hash to recipe to use source cache.
[32mINFO    [0m conda_build.metadata:metadata.py:854 Attempting to finalize metadata for r-meanr
[35mDEBUG   [0m conda_index.index:__init__.py:680 found subdirs {'linux-64', 'noarch'}
[35mDEBUG   [0m conda_index.index.sqlitecache:sqlitecache.py:102 CondaIndexCache channel_root=/usr/share/miniconda/envs/test/conda-bld, subdir=linux-64 db_filename=/usr/share/miniconda/envs/test/conda-bld/linux-64/.cache/cache.db cache_is_brand_new=False
[35mDEBUG   [0m conda_index.index.sqlitecache:sqlitecache.py:431 linux-64 listdir
[35mDEBUG   [0m conda_index.index.sqlitecache:sqlitecache.py:450 linux-64 save fs state
[35mDEBUG   [0m conda_index.index:__init__.py:759 linux-64 find packages to extract
[35mDEBUG   [0m conda_index.index:__init__.py:771 linux-64 extract 0 packages
[32mINFO    [0m conda_index.index:__init__.py:806 linux-64 cached 0 B from 0 packages at 0 B/second
[35mDEBUG   [0m conda_index.index.sqlitecache:sqlitecache.py:102 CondaIndexCache channel_root=/usr/share/miniconda/envs/test/conda-bld, subdir=noarch db_filename=/usr/share/miniconda/envs/test/conda-bld/noarch/.cache/cache.db cache_is_brand_new=False
[35mDEBUG   [0m conda_index.index.sqlitecache:sqlitecache.py:431 noarch listdir
[35mDEBUG   [0m conda_index.index.sqlitecache:sqlitecache.py:450 noarch save fs state
[35mDEBUG   [0m conda_index.index:__init__.py:759 noarch find packages to extract
[35mDEBUG   [0m conda_index.index:__init__.py:771 noarch extract 0 packages
[32mINFO    [0m conda_index.index:__init__.py:806 noarch cached 0 B from 0 packages at 0 B/second
[32mINFO    [0m conda_index.index:__init__.py:578 Completed linux-64
[32mINFO    [0m conda_index.index:__init__.py:578 Completed noarch
[35mDEBUG   [0m conda_index.index:__init__.py:680 found subdirs {'linux-64', 'noarch'}
[32mINFO    [0m conda_index.index:__init__.py:653 Channeldata subdir: linux-64
[35mDEBUG   [0m conda_index.index:__init__.py:654 linux-64 read repodata
[35mDEBUG   [0m conda_index.index.sqlitecache:sqlitecache.py:102 CondaIndexCache channel_root=/usr/share/miniconda/envs/test/conda-bld, subdir=linux-64 db_filename=/usr/share/miniconda/envs/test/conda-bld/linux-64/.cache/cache.db cache_is_brand_new=False
[35mDEBUG   [0m conda_index.index:__init__.py:662 linux-64 channeldata finished
[32mINFO    [0m conda_index.index:__init__.py:653 Channeldata subdir: noarch
[35mDEBUG   [0m conda_index.index:__init__.py:654 noarch read repodata
[35mDEBUG   [0m conda_index.index.sqlitecache:sqlitecache.py:102 CondaIndexCache channel_root=/usr/share/miniconda/envs/test/conda-bld, subdir=noarch db_filename=/usr/share/miniconda/envs/test/conda-bld/noarch/.cache/cache.db cache_is_brand_new=False
[35mDEBUG   [0m conda_index.index:__init__.py:662 noarch channeldata finished
[35mDEBUG   [0m conda_index.index:__init__.py:1155 _maybe_write /usr/share/miniconda/envs/test/conda-bld/index.html to /usr/share/miniconda/envs/test/conda-bld/index.html
[35mDEBUG   [0m conda_index.index:__init__.py:670 write channeldata
[35mDEBUG   [0m conda_index.index:__init__.py:1155 _maybe_write /usr/share/miniconda/envs/test/conda-bld/channeldata.json to /usr/share/miniconda/envs/test/conda-bld/channeldata.json