[35mDEBUG   [0m conda_index.index:__init__.py:680 found subdirs {'linux-64', 'noarch'}
[35mDEBUG   [0m conda_index.index.sqlitecache:sqlitecache.py:101 CondaIndexCache channel_root=/usr/share/miniconda/envs/test/conda-bld, subdir=linux-64 db_filename=/usr/share/miniconda/envs/test/conda-bld/linux-64/.cache/cache.db cache_is_brand_new=False
[35mDEBUG   [0m conda_index.index.sqlitecache:sqlitecache.py:431 linux-64 listdir
[35mDEBUG   [0m conda_index.index.sqlitecache:sqlitecache.py:450 linux-64 save fs state
[35mDEBUG   [0m conda_index.index:__init__.py:759 linux-64 find packages to extract
[35mDEBUG   [0m conda_index.index:__init__.py:771 linux-64 extract 0 packages
[32mINFO    [0m conda_index.index:__init__.py:801 linux-64 cached 0 B from 0 packages at 0 B/second
[35mDEBUG   [0m conda_index.index.sqlitecache:sqlitecache.py:101 CondaIndexCache channel_root=/usr/share/miniconda/envs/test/conda-bld, subdir=noarch db_filename=/usr/share/miniconda/envs/test/conda-bld/noarch/.cache/cache.db cache_is_brand_new=False
[35mDEBUG   [0m conda_index.index.sqlitecache:sqlitecache.py:431 noarch listdir
[35mDEBUG   [0m conda_index.index.sqlitecache:sqlitecache.py:450 noarch save fs state
[35mDEBUG   [0m conda_index.index:__init__.py:759 noarch find packages to extract
[35mDEBUG   [0m conda_index.index:__init__.py:771 noarch extract 0 packages
[32mINFO    [0m conda_index.index:__init__.py:801 noarch cached 0 B from 0 packages at 0 B/second
[32mINFO    [0m conda_index.index:__init__.py:578 Completed linux-64
[32mINFO    [0m conda_index.index:__init__.py:578 Completed noarch
[35mDEBUG   [0m conda_index.index:__init__.py:680 found subdirs {'linux-64', 'noarch'}
[32mINFO    [0m conda_index.index:__init__.py:653 Channeldata subdir: linux-64
[35mDEBUG   [0m conda_index.index:__init__.py:654 linux-64 read repodata
[35mDEBUG   [0m conda_index.index.sqlitecache:sqlitecache.py:101 CondaIndexCache channel_root=/usr/share/miniconda/envs/test/conda-bld, subdir=linux-64 db_filename=/usr/share/miniconda/envs/test/conda-bld/linux-64/.cache/cache.db cache_is_brand_new=False
[35mDEBUG   [0m conda_index.index:__init__.py:662 linux-64 channeldata finished
[32mINFO    [0m conda_index.index:__init__.py:653 Channeldata subdir: noarch
[35mDEBUG   [0m conda_index.index:__init__.py:654 noarch read repodata
[35mDEBUG   [0m conda_index.index.sqlitecache:sqlitecache.py:101 CondaIndexCache channel_root=/usr/share/miniconda/envs/test/conda-bld, subdir=noarch db_filename=/usr/share/miniconda/envs/test/conda-bld/noarch/.cache/cache.db cache_is_brand_new=False
[35mDEBUG   [0m conda_index.index:__init__.py:662 noarch channeldata finished
[35mDEBUG   [0m conda_index.index:__init__.py:1155 _maybe_write /usr/share/miniconda/envs/test/conda-bld/index.html to /usr/share/miniconda/envs/test/conda-bld/index.html
[35mDEBUG   [0m conda_index.index:__init__.py:670 write channeldata
[35mDEBUG   [0m conda_index.index:__init__.py:1155 _maybe_write /usr/share/miniconda/envs/test/conda-bld/channeldata.json to /usr/share/miniconda/envs/test/conda-bld/channeldata.json
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:1003 Starting new HTTPS connection (1): fastapi.metacpan.org:443
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:456 https://fastapi.metacpan.org:443 "GET /v1/module/Perl::Lint HTTP/1.1" 200 None
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:456 https://fastapi.metacpan.org:443 "GET /v1/release/Perl-Lint HTTP/1.1" 200 None
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:1003 Starting new HTTPS connection (1): fastapi.metacpan.org:443
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:456 https://fastapi.metacpan.org:443 "GET /v1/release/Perl-Lint HTTP/1.1" 200 None
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:456 https://fastapi.metacpan.org:443 "GET /v1/module/B::Keywords HTTP/1.1" 200 None
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:456 https://fastapi.metacpan.org:443 "GET /v1/release/B-Keywords HTTP/1.1" 200 None
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:1003 Starting new HTTPS connection (1): fastapi.metacpan.org:443
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:456 https://fastapi.metacpan.org:443 "GET /v1/release/B-Keywords HTTP/1.1" 200 None
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:456 https://fastapi.metacpan.org:443 "GET /v1/module/List::MoreUtils HTTP/1.1" 200 None
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:456 https://fastapi.metacpan.org:443 "GET /v1/release/List-MoreUtils HTTP/1.1" 200 None
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:1003 Starting new HTTPS connection (1): fastapi.metacpan.org:443
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:456 https://fastapi.metacpan.org:443 "GET /v1/release/List-MoreUtils HTTP/1.1" 200 None
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:456 https://fastapi.metacpan.org:443 "GET /v1/module/Email::Address HTTP/1.1" 200 None
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:456 https://fastapi.metacpan.org:443 "GET /v1/release/Email-Address HTTP/1.1" 200 None
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:1003 Starting new HTTPS connection (1): fastapi.metacpan.org:443
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:456 https://fastapi.metacpan.org:443 "GET /v1/release/Email-Address HTTP/1.1" 200 None
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:456 https://fastapi.metacpan.org:443 "GET /v1/module/List::Flatten HTTP/1.1" 200 None
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:456 https://fastapi.metacpan.org:443 "GET /v1/release/List-Flatten HTTP/1.1" 200 None
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:1003 Starting new HTTPS connection (1): fastapi.metacpan.org:443
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:456 https://fastapi.metacpan.org:443 "GET /v1/release/List-Flatten HTTP/1.1" 200 None
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:456 https://fastapi.metacpan.org:443 "GET /v1/module/String::CamelCase HTTP/1.1" 200 None
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:456 https://fastapi.metacpan.org:443 "GET /v1/release/String-CamelCase HTTP/1.1" 200 None
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:1003 Starting new HTTPS connection (1): fastapi.metacpan.org:443
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:456 https://fastapi.metacpan.org:443 "GET /v1/release/String-CamelCase HTTP/1.1" 200 None
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:456 https://fastapi.metacpan.org:443 "GET /v1/module/Compiler::Lexer HTTP/1.1" 200 None
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:456 https://fastapi.metacpan.org:443 "GET /v1/release/Compiler-Lexer HTTP/1.1" 200 None
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:1003 Starting new HTTPS connection (1): fastapi.metacpan.org:443
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:456 https://fastapi.metacpan.org:443 "GET /v1/release/Compiler-Lexer HTTP/1.1" 200 None
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:456 https://fastapi.metacpan.org:443 "GET /v1/module/Path::Tiny HTTP/1.1" 200 None
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:456 https://fastapi.metacpan.org:443 "GET /v1/release/Path-Tiny HTTP/1.1" 200 None
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:1003 Starting new HTTPS connection (1): fastapi.metacpan.org:443
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:456 https://fastapi.metacpan.org:443 "GET /v1/release/Path-Tiny HTTP/1.1" 200 None
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:456 https://fastapi.metacpan.org:443 "GET /v1/module/Test::Deep::NoTest HTTP/1.1" 200 None
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:456 https://fastapi.metacpan.org:443 "GET /v1/release/Test-Deep HTTP/1.1" 200 None
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:1003 Starting new HTTPS connection (1): fastapi.metacpan.org:443
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:456 https://fastapi.metacpan.org:443 "GET /v1/release/Test-Deep-NoTest HTTP/1.1" 404 None
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:1003 Starting new HTTPS connection (1): fastapi.metacpan.org:443
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:456 https://fastapi.metacpan.org:443 "GET /v1/module/Test::Deep::NoTest HTTP/1.1" 200 None
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:456 https://fastapi.metacpan.org:443 "GET /v1/module/Regexp::Lexer HTTP/1.1" 200 None
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:456 https://fastapi.metacpan.org:443 "GET /v1/release/Regexp-Lexer HTTP/1.1" 200 None
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:1003 Starting new HTTPS connection (1): fastapi.metacpan.org:443
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:456 https://fastapi.metacpan.org:443 "GET /v1/release/Regexp-Lexer HTTP/1.1" 200 None
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:456 https://fastapi.metacpan.org:443 "GET /v1/module/Module::Build::Tiny HTTP/1.1" 200 None
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:456 https://fastapi.metacpan.org:443 "GET /v1/release/Module-Build-Tiny HTTP/1.1" 200 None
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:1003 Starting new HTTPS connection (1): fastapi.metacpan.org:443
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:456 https://fastapi.metacpan.org:443 "GET /v1/release/Module-Build-Tiny HTTP/1.1" 200 None
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:456 https://fastapi.metacpan.org:443 "GET /v1/module/Capture::Tiny HTTP/1.1" 200 None
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:456 https://fastapi.metacpan.org:443 "GET /v1/release/Capture-Tiny HTTP/1.1" 200 None
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:1003 Starting new HTTPS connection (1): fastapi.metacpan.org:443
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:456 https://fastapi.metacpan.org:443 "GET /v1/release/Capture-Tiny HTTP/1.1" 200 None
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:456 https://fastapi.metacpan.org:443 "GET /v1/module/Test::Base::Less HTTP/1.1" 200 None
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:456 https://fastapi.metacpan.org:443 "GET /v1/release/Text-TestBase HTTP/1.1" 200 None
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:1003 Starting new HTTPS connection (1): fastapi.metacpan.org:443
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:456 https://fastapi.metacpan.org:443 "GET /v1/release/Test-Base-Less HTTP/1.1" 404 None
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:1003 Starting new HTTPS connection (1): fastapi.metacpan.org:443
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:456 https://fastapi.metacpan.org:443 "GET /v1/module/Test::Base::Less HTTP/1.1" 200 None
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:1003 Starting new HTTPS connection (1): cpan.metacpan.org:443
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:456 https://cpan.metacpan.org:443 "GET /authors/id/M/MO/MOZNION/CHECKSUMS HTTP/1.1" 200 84052