[32mINFO    [0m binstar:config.py:149 Using Anaconda API: https://api.anaconda.org
[35mDEBUG   [0m binstar:config.py:152 Using token from command line args
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:1007 Starting new HTTPS connection (1): api.anaconda.org:443
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:465 https://api.anaconda.org:443 "GET /package/conda_build_test/test_token_upload_419b0cc5ec5e4d61b610abcfdbfe25e8 HTTP/1.1" 404 None
[32mINFO    [0m conda_build.variants:variants.py:235 Adding in variants from config.variant
[32mINFO    [0m conda_build.metadata:metadata.py:854 Attempting to finalize metadata for test_token_upload_419b0cc5ec5e4d61b610abcfdbfe25e8
[32mINFO    [0m conda_build.build:build.py:2280 Packaging test_token_upload_419b0cc5ec5e4d61b610abcfdbfe25e8
[33mWARNING [0m conda_build.build:build.py:1627 No files or script found for output test_token_upload_419b0cc5ec5e4d61b610abcfdbfe25e8
[32mINFO    [0m conda_build.utils:utils.py:1970 Renaming work directory '/home/runner/work/_temp/serial/test_token_upload0/test_token_upload_419b0cc5ec5e4d61b610abcfdbfe25e8_1673024011407/work' to '/home/runner/work/_temp/serial/test_token_upload0/test_token_upload_419b0cc5ec5e4d61b610abcfdbfe25e8_1673024011407/work_moved_test_token_upload_419b0cc5ec5e4d61b610abcfdbfe25e8-1.0-1_linux-64_main_build_loop'
[32mINFO    [0m conda_build.utils:utils.py:1977 shutil.move(work)=/home/runner/work/_temp/serial/test_token_upload0/test_token_upload_419b0cc5ec5e4d61b610abcfdbfe25e8_1673024011407/work, dest=/home/runner/work/_temp/serial/test_token_upload0/test_token_upload_419b0cc5ec5e4d61b610abcfdbfe25e8_1673024011407/work_moved_test_token_upload_419b0cc5ec5e4d61b610abcfdbfe25e8-1.0-1_linux-64_main_build_loop)
[32mINFO    [0m binstar:config.py:149 Using Anaconda API: https://api.anaconda.org
[35mDEBUG   [0m binstar:config.py:152 Using token from command line args
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:1007 Starting new HTTPS connection (1): api.anaconda.org:443
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:465 https://api.anaconda.org:443 "GET /package/conda_build_test/test_token_upload_419b0cc5ec5e4d61b610abcfdbfe25e8 HTTP/1.1" 404 None